### ISSUE TITLE
Support symbol sources without checking SSL certs

### ISSUE THREAD

**Issue by loewenheim** [getsentry/symbolicator#1402]
We have experienced problems accessing the NVIDIA symbol source because of broken SSL certs¹. We should introduce a `reqwest` client that skips certificate checking (via https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.danger_accept_invalid_certs) and a per-source flag for enabling/disabling SSL.

¹ Or, more accurately, SSL certs we can't check.
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/symbolicator/pull/1403
- [ ] https://github.com/getsentry/symbolicator/pull/1404
- [ ] https://github.com/getsentry/symbolicator/pull/1405
- [ ] https://github.com/getsentry/sentry/pull/66509
```

**Comment by loewenheim** [comment]
Concerns about the security implications and lack of pressing urgency to do this have been raised in the discussion of #1404:
https://github.com/getsentry/symbolicator/pull/1404#issuecomment-1981379793
https://github.com/getsentry/symbolicator/pull/1404#issuecomment-1983109880
