### ISSUE TITLE
Tracking Issue: Replace Breakpad with rust-minidump

### ISSUE THREAD

**Issue by jan-auer** [getsentry/symbolicator#620]
Following @Gankra's tweet, I'm starting to play around to replace Breakpad with [`rust-minidump`](https://github.com/luser/rust-minidump). This is a side project in personal time right now, and even though I have it symbolicating and almost passing tests locally, it might drag out a little. In this issue, I'm collecting a living list of required changes. I'll be creating issues and PRs for all these.

In `rust-minidump`:
- [x] https://github.com/luser/rust-minidump/issues/371
- [x] https://github.com/luser/rust-minidump/issues/372
    - keeping our enum, but will investigate issue
- [x] Use `debugid::{DebugId, CodeId}` rather than Strings for module identifiers
- [ ] Add an error variant to `ProcessError` to allow surfacing custom errors from the symbol provider
- [x] Add a `thread_id` field to `CallStack`, or better even the entire `raw::MinidumpThread`
- [x] Fix up `code_identifier` for MachO modules. Returns some garbage now, should return the LC_UUID ([see also](https://github.com/getsentry/breakpad/blob/2aaba88045393a024b0e8d285fd2a416c4e05ff4/src/processor/minidump.cc#L2026-L2036)). 
    - luser/rust-minidump#438
- [x] Provide simpler interfaces to enumerate valid registers from frames
    - https://github.com/luser/rust-minidump/pull/414
- [x] Normalize Linux OS version info similar to [symbolic](https://github.com/getsentry/symbolic/blob/6b3f424a60dcffa31fbde1deccde3ac6e1bbc0bd/symbolic-minidump/src/processor.rs#L856-L865).
    - luser/rust-minidump#457
- [x] Add an equivalent to Breakpad's `ReturnAddress`, which is overridden in x86 and amd64 in Breakpad 
    - https://github.com/luser/rust-minidump/pull/415

Here:
- [x] Investigate stackwalker diffs
- [x] Check why `Module::debug_identifier` is optional
- [ ] Evaluate whether we can just rely on `Instruction` rather than applying our own heuristics (requires code changes in the generic symbolizer path though)
- [x] Check ARM instruction pointer semantics (Breakpad had heuristics applied, see [here](https://github.com/getsentry/symbolic/blob/6b3f424a60dcffa31fbde1deccde3ac6e1bbc0bd/symbolic-minidump/src/processor.rs#L737-L746))

This is an incomplete list, and I'll amend it as I make progress. Current state can be viewed in [`ref/rust-minidump`](https://github.com/getsentry/symbolicator/tree/ref/rust-minidump). Note that it uses patches of rust-minidump.
